- pipeline:
    name: mail
    description: |
      Newly uploaded patchsets enter this pipeline to receive an
      initial +/-1 Verified vote.
    manager: independent
    trigger:
      github:
        - event: pull_request
          action:
            - opened
            - changed
            - reopened
        - event: pull_request
          action: comment
          comment: (?i)^\s*recheck\s*$
    start:
      github:
        status: pending
        comment: false
        status-url: http://80.158.17.129/status/change/{change.number},{change.patchset}
    success:
      github:
        status: 'success'
      smtp:
        from: info@openlabtesting.org
        to: wangxiyuan1007@gmail.com
        subject: Success

    failure:
      github:
        status: 'failure'
        from: info@openlabtesting.org
        to: wangxiyuan1007@gmail.com
        subject: Failed


- project:
    name: moo-ai/test_openlab_ha
    mail:
      jobs:
        - test-mail


- job:
    name: test-mail
    parent: init-test
    timeout: 36000
    description: |
      Test mail
    run: .zuul/playbooks/test-mail/run.yaml
    nodeset: ubuntu-xenial
