- project:
    name: moo-ai/test_openlab_ha
    mail:
      jobs:
        - test-mail


- job:
    name: test-mail
    parent: init-test
    timeout: 3600
    description: |
      Test mail
    run: .zuul/playbooks/test-mail/run.yaml
    nodeset: ubuntu-xenial-arm64
