- project:
    name: moo-ai/test_openlab_ha
    check:
      jobs:
        - test


- job:
    name: test
    parent: init-test
    timeout: 3600
    description: |
      Test
    run: .zuul/playbooks/test-mail/run.yaml
    nodeset: ubuntu-huawei-arm
